language: scala
jdk: openjdk11
scala:
  - 2.12.12
sudo: false
before_install: umask 0022
script:
  - sbt -jvm-opts travis/jvmopts.compile compile
  - sbt -jvm-opts travis/jvmopts.compile run
  - sbt -jvm-opts travis/jvmopts.test test
